export const GET_TASKS = 'GET_TASKS'
export const ADD_TASK = 'ADD_TASK'
export const CREATE_MESSAGE = 'CREATE_MESSAGE'
export const GET_ERRORS = 'GET_ERRORS'
export const MARK_COMPLETE = 'MARK_COMPLETE'
